---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Henrygongzy.
--- DateTime: 25-1-5 下午3:25
---

require("__planet-portal__.prototypes.entity")
require("__planet-portal__.prototypes.item")
require("__planet-portal__.prototypes.recipe")
require("__planet-portal__.prototypes.technology")

data:extend({
    {
        type = "custom-input",
        name = "portal-configure",
        key_sequence = "mouse-button-1",
        consuming = "none"
    }
})