---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Henrygongzy.
--- DateTime: 25-1-5 下午3:25
---

--- item
local portal_underground_belt = table.deepcopy(data.raw["belt"]["underground-belt"])
local portal_fast_underground_belt = table.deepcopy(data.raw["belt"]["fast-underground-belt"])
local portal_express_underground_belt = table.deepcopy(data.raw["belt"]["express-underground-belt"])
local portal_turbo_underground_belt = table.deepcopy(data.raw["belt"]["turbo-underground-belt"])

-- update underground_belt
portal_underground_belt.name = "portal-underground-belt"
portal_underground_belt.icon = "__base__/graphics/icons/underground-belt.png"
portal_underground_belt.max_distance = 1
portal_underground_belt.minable.mining_time = 0.2

-- update fast_underground_belt
portal_fast_underground_belt.name = "portal-fast-underground-belt"
portal_fast_underground_belt.icon = "__base__/graphics/icons/fast-underground-belt.png"
portal_fast_underground_belt.max_distance = 1
portal_fast_underground_belt.minable.mining_time = 0.2

-- update express_underground_belt
portal_express_underground_belt.name = "portal-express-underground-belt"
portal_express_underground_belt.icon = "__base__/graphics/icons/express-underground-belt.png"
portal_express_underground_belt.max_distance = 1
portal_express_underground_belt.minable.mining_time = 0.2

-- update turbo_underground_belt
portal_turbo_underground_belt.name = "portal-turbo-underground-belt"
portal_turbo_underground_belt.icon = "__space-age__/graphics/icons/turbo-underground-belt.png"
portal_turbo_underground_belt.max_distance = 1
portal_turbo_underground_belt.minable.mining_time = 0.2

data:extend(portal_underground_belt, portal_fast_underground_belt,
            portal_express_underground_belt, portal_turbo_underground_belt)

---recipe
local portal_underground_belt_recipe = {
    type = "recipe",
    name = "portal-underground-belt",
    ingredients =
    {
        {type = "item", name = "underground-belt", amount=4},
    },
    results = {{type="item", name="portal-underground-belt", amount=2}}
}

local portal_fast_underground_belt_recipe = {
    type = "recipe",
    name = "portal-fast-underground-belt",
    ingredients =
    {
        {type = "item", name = "fast-underground-belt", amount=4},
    },
    results = {{type="item", name="portal-fast-underground-belt", amount=2}}
}

local portal_express_underground_belt_recipe = {
    type = "recipe",
    name = "portal-express-underground-belt",
    ingredients =
    {
        {type = "item", name = "express-underground-belt", amount=4},
    },
    results = {{type="item", name="portal-express-underground-belt", amount=2}}
}

local portal_turbo_underground_belt_recipe = {
    type = "recipe",
    name = "portal-turbo-underground-belt",
    ingredients =
    {
        {type = "item", name = "turbo-underground-belt", amount=4},
    },
    results = {{type="item", name="portal-turbo-underground-belt", amount=2}}
}

data:extend(portal_underground_belt_recipe, portal_fast_underground_belt_recipe,
            portal_express_underground_belt_recipe, portal_turbo_underground_belt_recipe)